#!/bin/bash

# Global constant for hooks directory
HOOKS_DIR="$HOME/.git/hooks"
SCRIPT_URL="https://raw.githubusercontent.com/hamed-rezaee/flutter-git-hook-scripts/main/pre-push"

# Function to print error messages
error() {
  echo "Error: $1" >&2

  exit 1
}

# Check if a command exists
check_command() {
  if ! command -v "$1" &> /dev/null; then
    error "$2 command not found. Make sure $2 is installed and available in your PATH."
  fi
}

# Run command with error handling
run_command() {
  echo "$1"

  if ! eval "$1"; then
    error "$2"
  fi
}

# Function to create hooks directory
create_hooks_directory() {
  run_command "mkdir -p ${HOOKS_DIR}" "Failed to create hooks directory."
}

# Function to download hook script
download_hook_script() {
  cd "${HOOKS_DIR}" || error "Failed to navigate to hooks directory."
  
  run_command "curl -sS -o pre-push ${SCRIPT_URL}" "Failed to download the pre-push hook script."
}

# Function to make hook script executable
make_hook_executable() {
  cd "${HOOKS_DIR}" || error "Failed to navigate to hooks directory."
  
  run_command "chmod u+x pre-push" "Failed to make the hook script executable."
}

# Function to configure Git to use hooks directory globally
configure_git_hooks_directory() {
  run_command "git config --global core.hookspath ${HOOKS_DIR}" "Failed to configure Git to use hooks directory globally."
}

# Function to inform user about successful setup
inform_success() {
  echo "Git hook setup completed successfully."
}

# Main function to execute setup
main() {
  # Check if curl is installed
  check_command curl Curl

  # Create hooks directory if it doesn't exist
  create_hooks_directory
  
  # Download the pre-push hook script
  download_hook_script
  
  # Make the hook script executable
  make_hook_executable
  
  # Configure Git to use the hooks directory globally
  configure_git_hooks_directory
  
  # Inform the user about the successful setup
  inform_success
}

# Execute the main function
main
