#!/bin/bash

# Check if curl is installed
if ! command -v curl &> /dev/null; then
    echo "Error: curl command not found. Please install curl." >&2
    exit 1
fi

# Create hooks directory if it doesn't exist
hooks_dir=~/.git/hooks
mkdir -p "$hooks_dir"

# Navigate to hooks directory
cd "$hooks_dir" || exit

# Download the pre-push hook script
curl_output=$(curl -sS -o pre-push https://raw.githubusercontent.com/hamed-rezaee/flutter-git-hook-scripts/main/pre-push)

# Check if download was successful
if [ $? -ne 0 ]; then
    echo "Error: Failed to download the pre-push hook script." >&2
    exit 1
fi

# Make the hook script executable
chmod u+x pre-push

# Configure Git to use the hooks directory globally
git config --global core.hookspath "$hooks_dir"

# Inform the user about the successful setup
echo "Git hook setup completed successfully."

exit 0
